### ISSUE TITLE
All but the first group discovery does not work.

### ISSUE THREAD

**Issue by KenHamilton** [thekevinholman/MultiHomeSCOMAgents#1]
[Version 1.0.1.0] 
1. Only the first Discovery runs and populates the group successfully
2. GW1 discovery is enabled by default (intended?)
3. GW2 discovery rule targets the GW1 class

Once correcting item 3 and all relevant discoveries are configured and enabled only the first discovery actually populates its group.
Sometimes I see other event log entries for the other discoveries, but the group/s are never populated.

Upon import I see some relationship-based errors in the OpsMgr EventLog.

**Comment by thekevinholman** [comment]
You were spot on.  I found the bugs and fixed them in this release.  Sorry it took so long.
